num-workers = 20
data-path = /home/vndo_umass_edu/splits_data/hpopt/lipo/data.csv
ensemble-size = 0
aggregation = norm
task-type = regression
epochs = 200
splits-file = /home/vndo_umass_edu/splits_data/hpopt/lipo/data.json
batch-size = 16
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
message-hidden-dim = 500
depth = 5
dropout = 0.15000000000000002
aggregation-norm = 100
activation = RELU
ffn-hidden-dim = 900
ffn-num-layers = 2
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 51
init-lr = 2.8977985912891204e-06
max-lr = 0.0002869983521518592
final-lr = 1.447099738706599e-05
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
data-seed = 0
